# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-12 15:30
from __future__ import unicode_literals

from __future__ import absolute_import
import django.contrib.postgres.fields.jsonb
from django.db import migrations

REVISION = '1.0.16'
DOWN_REVISION = '1.0.15'


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_uuid_field_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbnode',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='dbnode',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
        ),
    ]
