# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 13:59
from __future__ import unicode_literals

from __future__ import absolute_import
import django.contrib.postgres.fields.jsonb
from django.db import migrations

from aiida.backends.djsite.db.migrations import upgrade_schema_version


REVISION = '1.0.17'
DOWN_REVISION = '1.0.16'


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0016_django_1_11'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dbattribute',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='dbattribute',
            name='dbnode',
        ),
        migrations.AlterUniqueTogether(
            name='dbextra',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='dbextra',
            name='dbnode',
        ),
        migrations.AddField(
            model_name='dbnode',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dbnode',
            name='extras',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='DbAttribute',
        ),
        migrations.DeleteModel(
            name='DbExtra',
        ),
        upgrade_schema_version(REVISION, DOWN_REVISION),
    ]
